### ISSUE TITLE
Feature Request - Reverse Cloze Types

### ISSUE THREAD

**Issue by abhishek7786** [nihil-admirari/modern-cloze-overlapper#6]
@nihil-admirari  thanks for the awesome cloze type.

Can you please add the functionality of adding reverse cloze type cards.

E.g.,->
.....[ClozeType 1::}....{ClozeType2:: Content::Hint)

It creates -> 3 cards

1st Card - For normal cloze 1.
2nd Card -> During review Only Hint is visible upon "Show Answer" Content is visible
3rd Card -> During review Only Content is visible upon "Show Answer" Hint is visible

**Comment by nihil-admirari** [comment]
It is not really possible. Cards are created by Anki, and in order to generate a card number 3, `{{c3::` must be present in the field. A sub-optimal workaround is to set `Text` to

```
... {{c1::cloze1}}{{c2::cloze1::cloze1}}{{c3::cloze1::cloze1}} ... {{c2::Front::Back}}{{c3::Back::Front}}
```

and `Before|After|OnlyContext|RevealAll|InactiveHints` to

```
0|0|true
```

It'll display `[cloze1]` (with brackets) on the fronts of cards 2 and 3. Complexity will increase considerably if more than 3 clozes are required; basically you'll have to duplicate the content of all the clozes that must be visible simultaneously with the current cloze.
